apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: victim
  name: victim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victim
  template:
    metadata:
      labels:
        app: victim
    spec:
      containers:
      - image: alpine:3.12
        name: victim
        command: ["sleep", "100000"]
