apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: victim
  name: victim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victim
  template:
    metadata:
      labels:
        app: victim
    spec:
      initContainers:
      - name: sysctl-setup
        image: alpine:3.12
        command: ["sh", "-c", "sysctl -w net.ipv6.conf.all.disable_ipv6=0; " +
                                "sysctl -w net.ipv6.conf.default.disable_ipv6=0; " +
                                "sysctl -w net.ipv6.conf.eth0.disable_ipv6=0; " +
                                "sysctl -w net.ipv6.conf.lo.disable_ipv6=0; " +
                                "sysctl -w net.ipv6.conf.all.accept_ra=1; " +
                                "sysctl -w net.ipv6.conf.default.accept_ra=1; " +
                                "sysctl -w net.ipv6.conf.eth0.accept_ra=1; " +
                                "sysctl -w net.ipv6.conf.lo.accept_ra=1"]
        securityContext:
          privileged: true
      containers:
      - image: alpine:3.12
        name: victim
        command: ["sleep", "100000"]
