apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: attacker
  name: attacker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attacker
  template:
    metadata:
      labels:
        app: attacker
    spec:
      containers:
      - image: knqyf263/cve-2020-10749
        name: attacker
